### ISSUE TITLE
On NameGenerator, Additional attributes 'add' button shows even when no more options to add

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Architect#325]
<img width="763" alt="screenshot 2018-11-19 at 14 41 32" src="https://user-images.githubusercontent.com/776599/48716001-3f453e80-ec0e-11e8-8ef6-7b021d449bc3.png">
<img width="624" alt="screenshot 2018-11-19 at 14 41 37" src="https://user-images.githubusercontent.com/776599/48716009-43715c00-ec0e-11e8-8e9e-6a3beba1e02b.png">

**Comment by rebeccamadsen** [comment]
I don't think this is relevant any longer, because you can now "create new" additional variables even if you've used all the previously created ones.
