### ISSUE TITLE
MultiSelect looks odd when fields contain errors.

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Architect#339]
Example:
<img src="https://user-images.githubusercontent.com/776599/48943593-9a7f7580-ef1b-11e8-91aa-25f2563431d3.png" />

**Comment by rebeccamadsen** [comment]
A lot has changed since this was created. I am not sure this is an issue any longer.

![image](https://user-images.githubusercontent.com/16093053/121730175-547c6400-cabd-11eb-81c1-8de9a2563117.png)
