### ISSUE TITLE
Testing generally inadequate

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Architect#428]
New features in the last release broke a lot of things in Architect. These things weren't immediately obvious when testing the app by hand, such as missing components on interfaces.

- We need to be able to check for regressions in the UI, perhaps based on the integration tests.
- Currently unit tests contain their own parcels of redux state/props, this means that tests continue to pass when prop/protocol changes are made in the app that break the app. Perhaps we should use a global mock state to make it simpler to keep parity with the app.

**Comment by jthrilly** [comment]
> * Currently unit tests contain their own parcels of redux state/props, this means that tests continue to pass when prop/protocol changes are made in the app that break the app. Perhaps we should use a global mock state to make it simpler to keep parity with the app.

This one in particular is really important, I think.

> We need to be able to check for regressions in the UI, perhaps based on the integration tests.

Can you say more about how this would work? Is this going back to the system we tried with NC?

**Comment by wwqrd** [comment]
> Can you say more about how this would work? Is this going back to the system we tried with NC?

Something like what we have here: https://github.com/codaco/integration-tests, with a web driver. Very high level tests. e.g. when I select a nodeType, prompts appear. What happened in the last build was that there was a conditional element which didn't appear, but didn't actually throw any errors - it's very difficult to spot manually.
