### ISSUE TITLE
"Rich" text entry for fields that support markdown

### ISSUE THREAD

**Issue by jthrilly** [complexdatacollective/Architect#452]
We should replace text entry fields where the underlying field supports markdown with a "rich" component that allows the user to click buttons for bold and underlined text. Something similar to the github issue box.

**Comment by jthrilly** [comment]
I see another cool example of this is the netlify CMS markdown widget: https://www.netlifycms.org/docs/widgets/#markdown

(You can see it working on our documentation site CMS)

Two features I like about it:
- you can specify which markdown features are supported
- it has a "minimal' mode, which uses a text input rather than a text area.

**Comment by rebeccamadsen** [comment]
Related to #631 and resolved in #709.
