### ISSUE TITLE
Manage codebook empty view, and shows ego section when no ego variables defined

### ISSUE THREAD

**Issue by jthrilly** [complexdatacollective/Architect#655]
The manage codebook screen shows a heading for Ego even when no ego variables are defined. It shouldn't do this.
<img width="1552" alt="Screen Shot 2020-06-30 at 1 19 19 PM" src="https://user-images.githubusercontent.com/1387940/86125286-4fa0e900-bad4-11ea-9e7e-edb4200f6964.png">

When removed, the view should show a richer explanation of what this view is for, including links to the documentation website.

**Comment by wwqrd** [comment]
Resolved by 85ace09667498cd8f0a00bcabd912829247db650
