### ISSUE TITLE
Development mode file loading issues on Windows platform

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Architect#669]
When running Architect in development mode on Windows (native, not WSL) file-based actions do not appear to complete. For example, when attempting to open a protocol the RESET and UNBUNDLE (redux) actions is called, but the thunk stops there.

This behaviour is not seen in the production build (all platforms), or development modes on the macOS and linux platforms.

**Comment by wwqrd** [comment]
On further investigation:
- This issue exists as far back as 4.20
- File writing aspects seem to be okay, but reading hangs
- If the the log is set to persist in the developer tools, when the electron app is refreshed the read actions then seem to complete.

Speculation:
- There is something up with our implementation, maybe a race condition.
- Electron/Webpack may be broken or improperly configured on this platform
- Some underlying technology has changed underneath which has retrospectively broken something

For now we have decided to work on the remaining project issues and potentially revisit this later.

**Comment by rebeccamadsen** [comment]
Closing, as this has been resolved in recent updates.
