### ISSUE TITLE
file association broken with a space in path

### ISSUE THREAD

**Issue by rebeccamadsen** [complexdatacollective/Architect#686]
Trying to double click on a `.netcanvas` file to open in Architect fails if there is a space in the username on windows. We get an error that the app can't run:

![cant run](https://user-images.githubusercontent.com/16093053/101182759-8ac3bd00-361c-11eb-8321-fb3a42b26e7c.jpg)

Right-clicking on the `.netcanvas` file shows that it thinks Architect is the correctly associated app (and the icon is further indication):

![open with](https://user-images.githubusercontent.com/16093053/101182785-90b99e00-361c-11eb-80ac-2412a002dc18.jpg)

Drilling into open with another app, the default app listed is just 'Big', which is the first part of my username (before a space):

![wrong path](https://user-images.githubusercontent.com/16093053/101182806-9911d900-361c-11eb-97b9-fb790d7a1809.jpg)

Somehow file association is getting the path for Architect wrong. If I look up the path to the app myself, it opens correctly.

**Comment by wwqrd** [comment]
I tried to repeat this on a fresh windows 10 installation with a user "test user" and it worked as expected. Might be best for you to look into this one @rebeccamadsen?

**Comment by rebeccamadsen** [comment]
I tried this with a new user account on my computer (so and so) and could not replicate, so it must be something funky with my personal log in. Perhaps I migrated my account from a previous version of Windows 10 or uninstalling and reinstalling so many times got something in a funky state? I'm inclined to close with the assumption it's my development environment and not a user facing issue.

**Comment by jthrilly** [comment]
Closing until we find a confirmed case.
