### ISSUE TITLE
No downloadable Appimage version

### ISSUE THREAD

**Issue by dirusulixes** [complexdatacollective/Architect#694]
The installation instructions refer to an Appimage package that I cannot see in the release page.

**Comment by jthrilly** [comment]
Hi @dirusulixes - you're absolutely correct. Sorry for the confusion with the documentation. 

We encountered some issues relating to sandboxing and Linux packaging, which we've not had time to investigate further at this point. If you are running a debian derivative, we put up deb packages linked here: https://github.com/complexdatacollective/Interviewer/issues/1108

I am happy to produce linux releases for you now. Can you let me know which package format would be preferable for you?
