### ISSUE TITLE
Edge shown as not in use when used in dyad census

### ISSUE THREAD

**Issue by jthrilly** [complexdatacollective/Architect#696]
When using the attached protocol in Architect, the codebook shows the ‘knows’ edge type is not in use, when it is (on the dyad census).

[Simple Entity Resolution Protocol.netcanvas.zip](https://github.com/complexdatacollective/Architect/files/5987310/Simple.Entity.Resolution.Protocol.netcanvas.zip)

**Comment by wwqrd** [comment]
Should be resolved by
- Replace Dyad Census edge selector https://github.com/complexdatacollective/Architect/pull/698
- Update indexer to include dyad routes https://github.com/complexdatacollective/Architect/pull/697
