### ISSUE TITLE
Extra <br /> tags in information screen item preview

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Architect#717]
On the information screen multiple new lines for a text block are shown as <br /> tags in the item preview. This is stripped when rendered in Interviewer (preview), and also parses correctly into a new line in the rich text editor. Seems like something the rich text serializer is doing.

- Update the preview (in the list in architect) to match the render settings in Interviewer
- Update the serializer to remove this behaviour?

**Comment by wwqrd** [comment]
`react-markdown` escapes html intentionally for security reasons. `remark-slate` serializes multiple line breaks into <br> tags.

Options are:
- Add html support to react-markdown (security implication with malicious protocols)
- Strip `<br>` tags from the serialized output (will cause mismatch between `<RichText>` preview and actual markdown output)
- Replace `<br>` tags in output with something that `react-markdown` supports. It's not clear if there is something suitable; double spaces only work when used in conjunction with copy.
- Update the slate instance to prevent multiple line breaks (may seem like broken behaviour to user)

**Comment by jthrilly** [comment]
I don't think we should be generating `<br />` tags from slate, so my first preference is to prevent that. Maybe we could replace them with empty paragraphs that contain a single (escaped) space. This would require updating the empty node detection.

Failing that, I think stripping them and accepting the mismatch between the editor and the output is the thing to do.

**Comment by rebeccamadsen** [comment]
I think this was resolved in #728. Or at least I can't replicate this now.
