### ISSUE TITLE
Printable protocol handbook

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Architect#723]
Allow the user to produce a printable summary a protocol for use by:
- Researchers: Assisting in the development of protocols and for training interviewers
- Data managers: Planning data cleaning and analysis
- IRBs: In order to vet protocols and see exactly what participants will see

# Requirements:

- Use React to "template" the document
- Use Electron's built in pdf generation: https://www.electronjs.org/docs/api/web-contents#contentsprinttopdfoptions

## Document contents

**Table of contents**

**Stage summary**
For each stage:
- Stage title
- Stage type thumbnail preview
- Stage type (e.g. Dyad Census)
- Stage category (e.g. Name generator)
- Text from the stage
- Variables used on stage
- Interviewer script

**Codebook summary**
For each entity:
- name
- used in
- preview

For each variable:
- name
- type
- input control
- used in
- potential values

**Asset summary**
For each network:
- name
- variables
- guessed type?

For each image/video file:
- name
- preview

For each audio file:
- name

**Comment by wwqrd** [comment]
Use React to "template" the document.

**Comment by jthrilly** [comment]
Implemented in #724
